name: "Deploy Preview Environment"
description: "Preview environments for your Docker Compose or Kubernetes applications"
inputs:
  name:
    description: "The name of the preview environment to create"
    required: true
  timeout:
    description: 'The length of time to wait for completion, zero means never. Any other values should contain a corresponding time unit e.g. 1s, 2m, 3h  (default 5m0s)'
    required: false
  scope:
    description: "The scope of preview env to create. Allowed values are: personal or global. Defaults to global."
    required: false
    default: "global"
  variables:
    description: 'Variables to be used by the pipeline. If several variables are present, they should be separated by commas e.g. VAR1=VAL1,VAR2=VAL2,VAR3=VAL3'
    required: false
  file:
    description: "Path to the manifest file"
    required: false
  branch:
    description: "The branch to deploy"
    required: false
  log-level:
    description: "Log level string. Valid options are debug, info, warn, error"
    required: false
  comment:
    description: "Specify custom comment. Prefix with @ to read from a file."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
    - --timeout=${{ inputs.timeout }}
    - --scope=${{ inputs.scope }}
    - --var=${{ inputs.variables }}
    - --file=${{ inputs.file }}
    - --branch=${{ inputs.branch }}
    - --log-level=${{ inputs.log-level }}
    - --comment=${{ inputs.comment }}
branding:
  color: 'green'
  icon: 'grid'
